---
- name: Install nginx and start
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Start service nginx
      service:
       name: nginx
       state: started
  