---
- name: Install git and start
  hosts: web
  become: yes
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
    - name: Start service git, if not started
      service:
      name: git
      state: started
  