---
- name: "variable form play level"
  hosts: localhost
  vars:
   course: "Devops"
   trainer: "pavan"
   duration: "110Hrs"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi I am learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"