---
- name: Task level variable declaration
  hosts: localhost
  vars:
   course: devops
   trainer: pavan
   duration: 110Hrs
  tasks:
  - name: task level variable
    vars:
     trainer: "Pavan Kumar Muvva"
     ansible.builtin.debug:
       msg: "Hi, I am learning {{course}}, trainer is {{trainer}}, duration is {{durations}}"