---
- name: Install package using loop function
  hosts: localhost
  become: yes
  tasks:
  - name: Install package
    ansible.builtin.package:
     name: "{{item}}"
     state: present
    loop:
    - git
    - mysql
    - nginx
    - ansible
     